# Generated by Django 5.0.9 on 2026-08-21 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qr_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('NOT_CHECKED_IN', 'Not checked in'), ('PENDING', 'Pending (badge printing)'), ('CHECKED_IN', 'Checked in')], default='NOT_CHECKED_IN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PRINTING', 'Printing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='checkin.attendee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'QUEUED')), fields=('attendee',), name='unique_queued_print_job_per_attendee'),
        ),
    ]
